# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Fonting-Awesome-Flatiron-CocoaPods' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'FontAwesomeKit', '~> 2.2.0'
  pod 'CWStatusBarNotification', '~> 2.3'
  # Pods for Fonting-Awesome-Flatiron-CocoaPods

  #target 'Fonting-Awesome-Flatiron-CocoaPodsTests' do
   # inherit! :search_paths
    # Pods for testing
    #pod 'FontAwesomeKit', '~> 2.2.0'
  #end

  #target 'Fonting-Awesome-Flatiron-CocoaPodsUITests' do
   # inherit! :search_paths
    # Pods for testing
  #end

end
